baseurl: "/"
title: "Spectral"
init_js: "assets/js/init.js"
page_load_js: "assets/js/page_load.js"
params:
  landing_template: home
  palette: blue
  palettes:
    blue:
      sass:
        accent1: "#4598c8"
        accent2: "#93d7ff"
        accent3: "#b8d5ff"
        accent4: "#a2f7c2"
        accent5: "#6289c3"
        accent6: "#53b678"
    green:
      sass:
        accent1: "#21b2a6"
        accent2: "#00ffcc"
        accent3: "#00f0ff"
        accent4: "#76ddff"
        accent5: "#505393"
        accent6: "#ed4933"
sass:
  input_file: sass/main.scss.njk
  output_file: assets/css/main.css
  indentWidth: 4
  outputStyle: nested
  precision: 10
templates:
  body_class: "{% if page.params.template == site.params.landing_template %}landing {% endif %}"
